### ISSUE TITLE
entity 관계 설정

### ISSUE THREAD

**Issue by best0611** [syxxne/career-up-spring#3]
## Description
1대다 관계 설정

## Todo
- [x] UserEntity, UserSkillEntity 1대다
- [x] UserEntity, UserFieldEntity 1대다
- [x] UserEntity, ChatInfoEntity 1대다

## ETC
기타사항

## References
- [참고자료](링크)
